INSERT INTO USER (NAME, EMAIL, PASSWORD) VALUES ('admin', 'admin@musinsa.com', '$2a$10$Jnq1GIZc7fZpQ2G70/VqK.q8BWVSi0K/Hl3BLvBPyyolcqdUB483.');

INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (1, '의류', 0);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (2, '상의', 1);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (3, '반팔 티셔츠', 2);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (4, '긴팔 티셔츠', 2);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (5, '아우터', 1);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (6, '후드 집업', 5);

INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (7, '바지', 0);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (8, '데님 팬츠', 7);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (9, '코튼 팬츠', 7);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (10, '숏 팬츠', 7);

INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (11, '신발', 0);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (12, '스니커츠', 11);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (13, '캔버스/단화', 12);
INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (14, '농구화', 12);

INSERT INTO CATEGORY (ID, VALUE, PARENTID) VALUES (15, '뷰티', 0);



